version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo-product-service
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-product-service:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    restart: unless-stopped